lib/src/lib.rs
lib/src/repository.rs
lib/src/sparql/mod.rs
lib/src/sparql/plan.rs
lib/src/store/memory.rs
lib/src/store/mod.rs
lib/src/store/rocksdb.rs
lib/tests/sparql_test_cases.rs
server/src/main.rs

Introduces `QueryOptions`.
`QueryOptions` is given to the `prepare` method in order to put in it things like the base IRI.
It uses the "builder" pattern:
- The default options are given by `QueryOptions::default()`
- There are multiple setters to override the default options like `fn with_base_iri(mut self, base_iri: &'a str) -> Self`
This way it solves the "empty `ServiceHandler` problem": the default option would be no ServiceHandler and, if the library user want to set a `ServiceHandler` they have to give a not empty one.

Allows to query the union all of graphs as the default graph

---

lib/src/lib.rs
lib/src/repository.rs
lib/src/sparql/eval.rs
lib/src/sparql/mod.rs
lib/src/sparql/model.rs
lib/src/sparql/plan.rs
lib/src/sparql/plan_builder.rs
lib/src/store/memory.rs
lib/src/store/mod.rs
lib/src/store/rocksdb.rs
lib/tests/service_test_cases.rs
lib/tests/sparql_test_cases.rs
server/src/main.rs

This is working! There are tests in the lib/tests folder. The one thing to note is that I found storing `QueryOptions` in `SimpleEvaluator` problematic because a lifetime variable needed to be threaded through all of the types. I moved it to be a parameter to `PreparedQuery::exec`, and returned `base_iri` as a parameter to `SimpleEvaluator::new`, but it can be overridden with the `QueryOptions` passed to `PreparedQuery::exec`. I also incorporated all of the feedback from your previous comments. Let me know if you have any feedback

Service query options

---

lib/src/model/blank_node.rs
lib/src/model/named_node.rs
lib/src/model/vocab.rs
lib/src/store/numeric_encoder.rs

The goal is to provide other crates with access to low-level term creation.
This is required, e.g., when binding to other languages (e.g. Python, JS) or other APIs (e.g. Sophia).

Open some inners of the library

---

lib/src/model/literal.rs

for the same reason as before: bindings to other languages/APIs can benefit from this

making unchecked constructor of Literal public

---

lib/src/model/blank_node.rs

Before that patch, it would return a string padded with null characters,
which is not a valid BLANK_NODE_IDENTIFIER in RDF syntaxes.

fix BlankNode::as_str

---

lib/src/model/literal.rs
lib/src/model/triple.rs

This is (again) useful for building bridges to other APIs.
Note that NamedNode already has this (into_string),
that BlankNode kind of has it (id)
and that Quad has incomplete versions of it (subject_owned, predicate_owned...).
So I don't think those are too disruptive.

add destruct method to Literal and Quad

---

lib/src/sparql/eval.rs
testsuite/oxigraph-tests/sparql/manifest.ttl
testsuite/oxigraph-tests/sparql/unbound_variable_in_subquery.rq
testsuite/oxigraph-tests/sparql/unbound_variable_in_subquery.srx

This is a bit naive and keeps out some interesting optimization.
We should be smarter and still propagate "always bound variables"
Closes #261

Variable should stay not bound in subqueries even if they are bound in the parent query

---

lib/src/sparql/eval.rs
lib/src/sparql/plan.rs
lib/src/sparql/plan_builder.rs

There is a project node just alongside aggregates so the key space is already bounded by it

Uses the same key space inside and outside of aggregate evaluation

---

lib/src/sparql/algebra.rs

As far as I can tell it previously wasn't possible to directly construct a `oxigraph` `Query` from a `spargebra` `Query` without serializing and deserializing.

Add conversion from spargebra Query into oxigraph Query

---

.github/dependabot.yml
python/README.md
python/pyproject.toml
python/requirements.dev.txt

Allows to avoid some unintended breakage if a build package introduces a breaking change

Set version constraints for Python build dependency

---

lib/src/sparql/update.rs
testsuite/oxigraph-tests/sparql/halloween_problem.ru
testsuite/oxigraph-tests/sparql/halloween_problem_result.ttl

Buffers all SPARQL UPDATE operation for DELETE/INSERT in order to avoid this problem.
This is quite heavy but RocksDB transaction already stay in memory, hence it won't change a lot the operation complexity.
The unit test for this problem was bad because the optimizer was hiding the problem.

SPARQL UPDATE: Fixes Halloween problem

---

.github/workflows/release.yml

We already publish both aarch64 and a amd64 wheels

Python macOS: Do not build universal2 wheels anymore

---

.github/workflows/artifacts.yml
.github/workflows/manylinux_build.sh
.github/workflows/release.yml
python/Cargo.toml

Prebuilt wheels are still using abi3 except for Linux where target-specific builds are also available

Python: Makes abi3 optional

---

lib/oxsdatatypes/src/date_time.rs
lib/src/sparql/eval.rs

Allows to be consistent with XPath and SPARQL 1.2 SEP 0002
This change is not replicated yet into the SPARQL evaluator to avoid a breaking change
https://www.w3.org/TR/xpath-functions/#func-subtract-dateTimes https://github.com/w3c/sparql-12/blob/main/SEP/SEP-0002/sep-0002.md

Makes Datetime.checked_sub return DayTimeDuration

---

lib/Cargo.toml
lib/oxsdatatypes/src/date_time.rs
lib/spargebra/Cargo.toml
lib/spargebra/src/algebra.rs
lib/spargebra/src/parser.rs
lib/src/sparql/eval.rs
lib/src/sparql/plan.rs
lib/src/sparql/plan_builder.rs

ADJUST is now only implemented when a new timezone is given. I am not sure "" for no timezone is the best way to go.
It is behind a sep-0002 feature in spargebra and sparql-smith and enabled by default in Oxigraph.

Implements SEP-0002 ADJUST function

---

Cargo.toml

Having it separated was failing fuzz tests for some unknown reason
This reverts commit d97eb9eb31e512d40a39ba81df1ff1e60ae7fdb7.
This reverts commit 4927b3148e3d26b1ab26bdbdf3d4080d6bbb5e56.

Add back oxrocksdb-sys to the main workspace

---

lib/sparql-smith/src/lib.rs

Unused because we already use Display to properly print the query

SPARQL smith: removes Debug derives

---

lib/oxsdatatypes/src/boolean.rs
lib/oxsdatatypes/src/date_time.rs
lib/oxsdatatypes/src/decimal.rs
lib/oxsdatatypes/src/double.rs
lib/oxsdatatypes/src/duration.rs
lib/oxsdatatypes/src/float.rs
lib/oxsdatatypes/src/integer.rs
lib/oxsdatatypes/src/lib.rs
lib/oxsdatatypes/src/parser.rs

Uses "ParseDecimalError" naming just like "ParseFloatError"

---

.github/workflows/tests.yml

Swatinem/rust-cache seems better than EmbarkStudios/cargo-deny-action to cache binaries

Installs cargo deny directly

---

Cargo.toml

Makes the WASM file go from 2.6MB to 2.3MB

JS: Optimizes release builds for size

---

server/Dockerfile

Allows to reduce the image size from 102MB to 42MB

Docker image: uses distroless base

---

Cargo.lock
bench/explanation_to_flamegraph.py
bench/explanation_to_trace.py
lib/Cargo.toml
lib/src/sparql/algebra.rs
lib/src/sparql/eval.rs
lib/src/sparql/mod.rs
lib/src/sparql/plan.rs
lib/src/sparql/plan_builder.rs
lib/src/sparql/update.rs
lib/src/store.rs
lib/tests/store.rs
server/src/main.rs

Only exposed in the CLI `query` command for now.
Example to get a flamegraph:
```bash
oxigraph_server query --location MY_DATA --query-file MY_QUERY --results-format csv --explain-file EXPLANATION.json --stats
python3 bench/explanation_to_flamegraph.py EXPLANATION.json FLAMEGRAPH.svg
```

Adds a simple explanation with profiling for SPARQL queries evaluation

---

lib/src/storage/mod.rs

This fixes a missing compaction of the GSPO index.
With dataset sizes and number of graphs growing, we've recently been seeing degrading query performance for some of our query workloads (made apparent via the new explain feature!). As we have a lot of point-like lookups (via GraphPatterns with all positions known) in our query plans, and this is the index chosen for those, we are probably disproportionally impacted by this.
With this fix a lot of our query times have decreased by ~50%.

Fix missing GSPO index compaction

---

lib/spargebra/src/term.rs

Spargebra: Makes GroundTermPattern::Triple properly gated with the rdf-star feature

---

.github/workflows/artifacts.yml
.github/workflows/musllinux_build.sh

Rust is moving to 1.2+: https://blog.rust-lang.org/2023/05/09/Updating-musl-targets.html

Python: drops compatibility with Musl 1.1

---

.github/workflows/artifacts.yml
.github/workflows/musllinux_build.sh

Reverts oxigraph/oxigraph#492
Pypa is not providing Musl 1.2 images yet See https://github.com/pypa/manylinux/issues/1488

Revert "Python: drops compatibility with Musl 1.1"

---

Cargo.lock
lib/sparql-smith/Cargo.toml
lib/sparql-smith/src/lib.rs

Result order is not kept by the optimizer.
We can't assume it is unchanged.

Fuzzer: do not consider OFFSET and LIMIT for now

---

python/src/io.rs
python/tests/test_io.py

Python text IO is counting by number of character
and not by number of bytes.
However, we were asking to read a number of bytes
and not a number of character,
leading to strange I/O exceptions being raised.

Python: fixes parsing from text I/O with not-ASCII char

---

.clusterfuzzlite/build.sh

CI is always failing because of https://github.com/tafia/quick-xml/issues/608

CI: Temporarily disable SPARQL XML results fuzzing

---

lib/oxsdatatypes/src/date_time.rs
lib/oxsdatatypes/src/parser.rs

Do not allow syntaxes not allowed by the grammar

Makes xsd:dateTime year parsing stricter

---

lib/src/sparql/eval.rs

It should return false and not fail...

Fixes || evaluation when all alternatives are false

---

python/src/model.rs

Not useful, always returns the empty string
Issue #257

Python: Removes DefaultGraph.value

---

.github/workflows/tests.yml
js/Cargo.toml
lib/Cargo.toml
lib/oxsdatatypes/Cargo.toml
lib/oxsdatatypes/README.md
lib/oxsdatatypes/src/date_time.rs
lib/oxsdatatypes/src/duration.rs
lib/src/sparql/algebra.rs
lib/src/sparql/eval.rs
lib/src/sparql/mod.rs

- Adds the "js" feature to enable JS support
- Adds the "custom-now" feature to oxsdatatypes to inject a custom "now" implementation It is already possible for random with the getrandom "custom" feature
Issue #471

Stop assuming JS platform when compiling to wasm32-unknown-unknown

---

lib/oxrdfio/src/parser.rs
lib/oxrdfio/src/serializer.rs
lib/oxrdfxml/src/parser.rs
lib/oxrdfxml/src/serializer.rs
lib/oxttl/src/n3.rs
lib/oxttl/src/nquads.rs
lib/oxttl/src/ntriples.rs
lib/oxttl/src/trig.rs
lib/oxttl/src/turtle.rs
lib/src/io/read.rs
lib/src/io/write.rs
server/src/main.rs

It is very rare to reuse parser and this allows to avoid copies

Makes parse_ and serialize_ method take owned Parser and Serializer

---

js/README.md
js/src/store.rs
python/src/io.rs
python/src/store.rs
python/tests/test_io.py
python/tests/test_store.py

- adds support of extensions
- MIME type is a deprecated wording

Python and & JS: Renames "mime_type" parameter to "format"

---

lib/oxsdatatypes/src/date_time.rs
lib/oxsdatatypes/src/duration.rs
lib/oxsdatatypes/src/lib.rs

P1M1D - P3D is giving 1M and -3D. This is not serializable with xsd:duration formatting

xsd:duration: properly fails when building not-serializable durations

---

.github/workflows/manylinux_build.sh
.github/workflows/musllinux_build.sh
Cargo.lock
cli/Cargo.toml
cli/Dockerfile
cli/README.md
cli/src/main.rs
lib/Cargo.toml
lib/README.md
lib/benches/store.rs
lib/src/sparql/http/dummy.rs
lib/src/sparql/http/mod.rs
lib/src/sparql/http/simple.rs
lib/src/sparql/mod.rs
lib/src/storage/backend/rocksdb.rs
lints/test_debian_compatibility.py
python/Cargo.toml
python/README.md

- Disables HTTPs support by default, the TLS stack is opt-in
- Renames "http_client" feature to "http-client"
- Uses native TLS by default in pyoxigraph and cli
- Uses Rustls for Linux Python wheels and Docker images

Upgrades oxhttp

---

lib/spargebra/src/parser.rs
testsuite/oxigraph-tests/sparql/ask_from.rq
testsuite/oxigraph-tests/sparql/manifest.ttl

Previously `ASK FROM` only worked without `WHERE`.
This did work:
```sparql
ASK FROM <scheme://a.graph> { FILTER(true) }
```
... but this did not:
```sparql
ASK FROM <scheme://a.graph> WHERE { FILTER(true) }
```

SPARQL: Fix ASK + FROM combination

---

lib/oxrdf/src/dataset.rs
lib/oxrdf/src/graph.rs
lib/oxttl/src/lexer.rs
lib/oxttl/src/line_formats.rs
lib/oxttl/src/n3.rs
lib/oxttl/src/terse.rs
lib/sparesults/src/solution.rs
lib/src/sparql/eval.rs

For consistency, ordered implementation of a traits the same way as they are declared.
Used `Self::<assoc>` in a few last spots

Linting: Impl ordering, Self refs

---

Cargo.toml

Smaller binaries, most of them where stripped out anyway

Removes all debuginfo from release build

---

lib/oxrdf/src/blank_node.rs
lib/oxrdf/src/triple.rs
lib/oxrdf/src/variable.rs
lib/oxrdfio/src/error.rs
lib/oxsdatatypes/src/date_time.rs
lib/oxsdatatypes/src/decimal.rs
lib/oxsdatatypes/src/duration.rs
lib/oxsdatatypes/src/integer.rs
lib/oxttl/src/trig.rs
lib/spargebra/src/algebra.rs
lib/spargebra/src/query.rs
lib/spargebra/src/term.rs
lib/spargebra/src/update.rs
lib/sparql-smith/src/lib.rs
lib/src/sparql/error.rs
testsuite/src/sparql_evaluator.rs

As seen in the https://rust.godbolt.org/z/Y8djWsq1P - `write!` macro produces significantly more code than a `write_str` call, so this change should have somewhat better performance.  To my knowledge, a lot of ppl tried to solve this optimization in the compiler, but no luck yet, so may help compiler ourselves for now.

Optimize `write!` performance with `write_str`

---

Cargo.lock

It keeps auto-updating, probably because of internal version changes. Ran `cargo update`

Bump Cargo.lock

---

.github/workflows/tests.yml
js/README.md
js/package.json
python/src/dataset.rs

Requires WASM reference types and JS WeakRef

JS: Drop older NodeJS and WebBrowsers support

---

Cargo.lock
Cargo.toml
lib/sparopt/Cargo.toml
lib/sparopt/src/optimizer.rs

This is done better by the remote endpoint and avoids harmful transformation like LATERAL insertion

sparopt: Avoid join reordering in SERVICE

---

js/README.md
js/src/store.rs
js/test/store.mjs

Adds more tests and documentation

JS: Properly serializes CONSTRUCT results using RDF formats rather than SPARQL results formats

---

js/benches/bench.mjs
js/src/store.rs

Also serializes query results to JSON

JS: Rename benchmark to avoid confusion with Rust benches

---

lib/spargebra/src/parser.rs

SPARQL parser: Fixes parsing of DESCRIBE queries with a space between FROM and WHERE

---

Cargo.toml

We are not catching panics and I believe we never got a panic bug report so unwind is likely not worth it

Abort instead of unwind on release builds

---

cli/src/main.rs
lib/oxttl/src/lexer.rs

Decode UTF-16 surrogate pairs and convert them to `char`s.
Linked issue: #925
Store `\uD83D\uDC68`
```
curl -v -X POST "localhost:7878/store?graph=http://g" -H "Content-Type: application/n-triples" -d "<http://a> <http://b> \"\\uD83D\\uDC68\" ."
```
```
HTTP/1.1 204 No Content
server: Oxigraph/0.4.0-alpha.7
```
Retrieve correct unicode
```
curl -v -X POST "localhost:7878/query" -H "Content-Type: application/sparql-query" -d "select ?o where { graph <http://g> { ?s ?p ?o } }"
```
```
HTTP/1.1 200 OK
content-type: application/sparql-results+json
server: Oxigraph/0.4.0-alpha.7
{"head":{"vars":["o"]},"results":{"bindings":[{"o":{"type":"literal","value":"👨"}}]}}
```

UTF-16 Surrogate Pair Support

---

lib/spargebra/src/parser.rs
testsuite/oxigraph-tests/sparql/construct_semicolon_dot.rq
testsuite/oxigraph-tests/sparql/manifest.ttl

SPARQL: Fixes CONSTRUCT parsing when dot follows semicolon

---

lib/oxigraph/src/sparql/eval.rs

GRAPH ?g { ?s !(...) ?o } was wrongly evaluated with ?g and ?s unbound and ?o bound

Fixes property path evaluation

---

lib/sparql-smith/Cargo.toml
lib/sparql-smith/src/lib.rs

Behavior depends on LATERAL optimization,
and it's the only way of making this feature useful

Fuzzer: do not fuzz unbound service

---

python/pyproject.toml

Rustc does it now by default and release builds

Python: remove explicit strip

---

lib/oxrdfxml/src/parser.rs

RDF/XML: properly ignore escaped whitespaces

---

.github/workflows/artifacts.yml

Allows still uploading the created wheels even when running into the timeout

CI: Adds a timeout to wheel builds

---

cli/README.md

... if this is incorrect, then it could maybe be rewritten for more clarity.

README: Typo: not -> now

---

fuzz/fuzz_targets/sparql_query.rs
fuzz/fuzz_targets/sparql_query_eval.rs
fuzz/fuzz_targets/sparql_update.rs
lib/oxigraph/src/sparql/algebra.rs
lib/spareval/README.md
lib/spareval/src/lib.rs
lib/spareval/src/model.rs
lib/spareval/src/service.rs
lib/spargebra/README.md
lib/spargebra/src/lib.rs
lib/spargebra/src/parser.rs
lib/spargebra/src/query.rs
lib/spargebra/src/update.rs
testsuite/src/sparql_evaluator.rs

Allows to set default prefixes

spargrebra: introduce the SparqlParser struct instead of Query::parse

---

cli/src/main.rs
cli/src/service_description.rs
fuzz/fuzz_targets/sparql_query_eval.rs
fuzz/fuzz_targets/sparql_update_eval.rs
js/src/store.rs
lib/oxigraph/README.md
lib/oxigraph/benches/store.rs
lib/oxigraph/src/sparql/algebra.rs
lib/oxigraph/src/sparql/mod.rs
lib/oxigraph/src/sparql/model.rs
lib/oxigraph/src/sparql/service.rs
lib/oxigraph/src/sparql/update.rs
lib/oxigraph/src/store.rs
lib/spargeo/src/lib.rs
python/src/sparql.rs
python/src/store.rs
testsuite/src/sparql_evaluator.rs

Allows injecting a bunch of options, both for SPARQL parsing and evaluation
Deprecations:
- Query and Update types
- (Store|Transaction).(query|update) methods

Introduce SPARQL fluent API SparqlEvaluator

---

cli/src/cli.rs
cli/src/main.rs
lib/oxigraph/src/sparql/mod.rs
lib/spareval/src/error.rs
lib/spareval/src/eval.rs
lib/spareval/src/lib.rs

It's a global boolean that allows to cancel a request. It is currently read on all RocksDB operations, it might mean some stalling on e.g. sorts or slow SERVICE calls.
Adds an option to the HTTP server to use the token for timeouts

SPARQL: adds a CancellationToken to cancel processing gracefully

---

lib/oxttl/src/lexer.rs
testsuite/serd-tests/good/test-lang.nt
testsuite/serd-tests/good/test-lang.ttl

This is allowed both by RFC5646 (referenced as BCP47 in https://www.w3.org/TR/turtle/) and the comment at the top of recognize_lang_tag()

oxttl: Add support for digits in language tag variant

---

lib/oxigraph/src/storage/rocksdb.rs

Otherwise they never get deleted

rocksdb: Remove SSTs after ingesting them

---

lib/spargebra/src/parser.rs
testsuite/oxigraph-tests/sparql/duplicated_values_var.rq
testsuite/oxigraph-tests/sparql/manifest.ttl

Example `VALUES (?a ?a) { (1 1) }`
See https://github.com/w3c/sparql-query/issues/293

SPARQL: fail parsing on repeated variables in VALUES
