lib/src/lib.rs
lib/src/repository.rs
lib/src/sparql/eval.rs
lib/src/sparql/mod.rs
lib/src/sparql/plan.rs
lib/src/sparql/plan_builder.rs
lib/src/store/memory.rs
lib/src/store/mod.rs
lib/src/store/rocksdb.rs
lib/tests/service_test_cases.rs
lib/tests/sparql_test_cases.rs
server/src/main.rs

* Codes simplifications
* Moves back `QueryOptions` into the `prepare` method.

Service support improvements

---

.github/workflows/build.yml
lib/Cargo.toml
lib/src/model/xsd/date_time.rs
lib/tests/wasm.rs

Adds WebAssembly support to Oxigraph lib

---

README.md
docker/Dockerfile
docker/README.md
docker/publish_docker_images.sh
server/Dockerfile
wikibase/Dockerfile

Adds docker-oxigraph

---

lib/Cargo.toml
lib/src/lib.rs
lib/src/sophia/model.rs
lib/src/sophia/store.rs
lib/tests/rocksdb_store.rs
lib/tests/sled_store.rs

Sorry I missed the release of v0.1.0 (very nice job, by the way).
Do you think it would be possible to include this in a v0.1.1?
Otherwise, it can wait until v0.2.0, there is no rush.

a feature to enable Sophia's traits implementation in Oxigraph

---

.github/workflows/artifacts.yml
.github/workflows/release.yml
js/README.md
js/build_package.js
js/package.json

Builds an hybrid web/node NPM module able to be used both in Node.JS and on modern web browsers.

Adds a web build to Oxigraph JS

---

lib/oxrdf/src/interning.rs
lib/src/xsd/decimal.rs
lib/src/xsd/duration.rs

Fix deprecated min/max values

---

lib/spargebra/src/parser.rs
testsuite/oxigraph-tests/sparql/manifest.ttl
testsuite/oxigraph-tests/sparql/nested_anonymous.rq
testsuite/oxigraph-tests/sparql/nested_anonymous.srx
testsuite/oxigraph-tests/sparql/nested_anonymous.ttl

SPARQL: Fixes parsing of nested anonymous blank nodes

---

python/src/io.rs
python/src/store.rs
python/tests/test_io.py

Adds support of reading from io.TextIOBase
Adds hidden support of reading from str and bytes
Improves test coverage

Makes Python I/O abstraction easier to use

---

.github/workflows/artifacts.yml
.github/workflows/manylinux_build.sh
.github/workflows/release.yml
.github/workflows/tests.yml
.gitignore
python/generate_stubs.py
python/mypy_allowlist.txt
python/pyproject.toml
python/requirements.dev.txt
python/src/io.rs
python/src/model.rs
python/src/sparql.rs
python/src/store.rs
python/tests/test_io.py
python/tests/test_model.py
python/tests/test_store.py

Adds a Python script to auto generate python stubs from the module code and doc strings.
Relies heavily on the `inspect` module.

Auto generate python stubs from doc strings

---

.github/workflows/tests.yml
python/generate_stubs.py
python/src/model.rs
python/src/store.rs

* Fixes some type annotations
* Adds python magic function overrides to stubs

Improves Python type stubs

---

.github/workflows/artifacts.yml
.github/workflows/release.yml

Let's only use readthedocs.org now

Drops oxigraph.org python doc updating

---

.github/workflows/tests.yml
lib/oxrdf/src/interning.rs
lib/oxrdf/src/parser.rs

Allows to check it works with features both enabled and disabled

Testsuite: Run clippy tests without optional features

---

python/src/model.rs

Fixes Python type annotation

---

server/src/main.rs

Safer with paths that are not valid UTF-8

Server: Uses PathBuf instead of string for I/O

---

server/src/main.rs

Server: Allows HTTP request to do bulk loading

---

.github/workflows/release.yml

Smaller than the Universal 2 wheel

Python wheel: releases also an ARM-only wheel

---

server/README.md

Suggest to use -T instead of --data in cUrl commands

---

python/src/io.rs
python/src/store.rs

It breaked Python 3.7 support for Mypy

Removes posonlyargs usages

---

lib/src/sparql/eval.rs
testsuite/oxigraph-tests/sparql/manifest.ttl
testsuite/oxigraph-tests/sparql/values_property_path_all.rq
testsuite/oxigraph-tests/sparql/values_property_path_all.srx

Fixes ZeroOrX path evaluation on terms that are not in the dataset but only in the query

---

fuzz/fuzz_targets/sparql_eval.rs
lib/sparql-smith/src/lib.rs
lib/src/sparql/eval.rs
lib/src/sparql/mod.rs
lib/src/sparql/plan.rs
lib/src/sparql/plan_builder.rs
lib/src/sparql/update.rs
testsuite/src/sparql_evaluator.rs

Hope to detect bugs in the query optimizer. Already allowed to find #317

Fuzzer: compares SPARQL evaluation with and without the optimizer 

---

lib/Cargo.toml
lib/oxrdf/Cargo.toml
lib/sparesults/Cargo.toml
lib/spargebra/Cargo.toml
oxrocksdb-sys/Cargo.toml
server/Cargo.toml

It is the actual MSRV of the last released version

Set Rust MSRV to 1.60

---

.github/workflows/tests.yml

CI: Removes test on push

---

fuzz/Cargo.toml
lib/Cargo.toml
lib/spargebra/Cargo.toml
lib/spargebra/src/algebra.rs
lib/spargebra/src/parser.rs
lib/sparql-smith/Cargo.toml
lib/sparql-smith/src/lib.rs
lib/src/sparql/eval.rs
lib/src/sparql/plan.rs
lib/src/sparql/plan_builder.rs
testsuite/oxigraph-tests/sparql/lateral/basic_input.ttl
testsuite/oxigraph-tests/sparql/lateral/filter.rq
testsuite/oxigraph-tests/sparql/lateral/graph.rq
testsuite/oxigraph-tests/sparql/lateral/join.rq
testsuite/oxigraph-tests/sparql/lateral/manifest.ttl
testsuite/oxigraph-tests/sparql/lateral/optional.rq
testsuite/oxigraph-tests/sparql/lateral/simple.srx
testsuite/oxigraph-tests/sparql/lateral/subselect.rq
testsuite/oxigraph-tests/sparql/lateral/subselect.srx
testsuite/oxigraph-tests/sparql/lateral/subselect_aggregate.rq
testsuite/oxigraph-tests/sparql/lateral/subselect_aggregate.srx
testsuite/oxigraph-tests/sparql/lateral/subselect_inside_optional.rq
testsuite/oxigraph-tests/sparql/lateral/subselect_inside_optional.srx
testsuite/oxigraph-tests/sparql/lateral/subselect_outside_optional.rq
testsuite/oxigraph-tests/sparql/lateral/subselect_outside_optional.srx
testsuite/oxigraph-tests/sparql/manifest.ttl
testsuite/tests/oxigraph.rs
testsuite/tests/parser.rs
testsuite/tests/sparql.rs

Follows SPARQL 1.2 SEP 0006. It is behind a sep-0006 feature in spargebra and sparql-smith and enabled by default in oxigraph.
Apache Jena tests are passing.
SEP 0006: https://github.com/w3c/sparql-12/blob/main/SEP/SEP-0006/sep-0006.md

Implements LATERAL join

---

testsuite/src/report.rs
testsuite/src/sparql_evaluator.rs

SPARQL test: displays query results diffs

---

.github/workflows/tests.yml
Cargo.lock
js/Cargo.toml
lib/Cargo.toml
lib/oxsdatatypes/Cargo.toml
lib/oxsdatatypes/src/date_time.rs
lib/src/sparql/http/dummy.rs
lib/src/storage/backend/fallback.rs
lib/src/storage/backend/mod.rs
lib/src/storage/binary_encoder.rs
lib/src/storage/mod.rs
lib/src/store.rs
lib/tests/store.rs

Adds tests for WASM+JS and WASI to the CI

Library: adds basic WASI support

---

js/build_package.js
js/package.json
js/rome.json
js/test/model.mjs
js/test/store.mjs

Provides a built-in linter.
Some formatting parameter are overriden to align with Rust and Python.

Js: Uses Rome instead of JS standard

---

lib/src/storage/backend/rocksdb.rs
lib/src/storage/mod.rs
lib/src/store.rs
lib/tests/store.rs
oxrocksdb-sys/api/c.cc
oxrocksdb-sys/api/c.h
server/src/main.rs

i saw #88 and thought i give it a try. this is of course not finished, it's more a sketch how i would implement this feature.  it should be enough to start a discussion, and exchange ideas, i've written some code comments when i was unsure how to do things.
i'm open for suggestions, still new to rust.
if you open the query page, and press the play button you should see a password prompt. the credentials are currently hard coded.

Server: Open readonly and secondary

---

.github/workflows/tests.yml
oxrocksdb-sys/api/.clang-format
oxrocksdb-sys/api/build_version.cc
oxrocksdb-sys/api/c.cc
oxrocksdb-sys/api/c.h

Uses the same configuration as RocksDB

Uses clang-format for C/C++ code

---

.clusterfuzzlite/build.sh
Cargo.lock
fuzz/Cargo.toml
fuzz/fuzz_targets/sparql_results_json.rs
fuzz/fuzz_targets/sparql_results_tsv.rs
fuzz/fuzz_targets/sparql_results_xml.rs
fuzz/src/lib.rs
fuzz/src/result_format.rs
lib/Cargo.toml
lib/oxrdf/Cargo.toml
lib/oxrdf/src/parser.rs
lib/sparesults/Cargo.toml
lib/sparesults/README.md
lib/sparesults/src/csv.rs
lib/sparesults/src/lib.rs
lib/sparesults/src/solution.rs
lib/sparesults/src/xml.rs
lib/spargebra/Cargo.toml
server/Cargo.toml
server/src/main.rs

See commit list for more details

Improvements to SPARQL results I/O

---

python/README.md
python/docs/index.rst
server/README.md

Adds link to the conda-forge package

---

lib/sparesults/src/json.rs
testsuite/oxigraph-tests/sparql-results/late_head.srj
testsuite/oxigraph-tests/sparql-results/late_head_expected.srj
testsuite/oxigraph-tests/sparql-results/manifest.ttl
testsuite/oxigraph-tests/sparql-results/typed_literal_expected.srj
testsuite/src/sparql_evaluator.rs

Does not do streaming parsing in this case

JSON SPARQL results: allows the "head" key to be at the end of the file

---

server/src/main.rs

Allows to get explicit errors if flush fails when closing the store

Server: adds explicit flush calls

---

python/generate_stubs.py
python/src/model.rs
python/tests/test_model.py

Allows positional pattern matching
Closes #449

Python: Adds __match_args__ definition where relevant

---

lib/Cargo.toml
lib/src/storage/backend/rocksdb.rs

Hidden behind the "rocksdb_debug" features

Allows to collect RocksDB statistics

---

lib/src/sparql/eval.rs
testsuite/src/sparql_evaluator.rs

Aggregators should return their default value (0 for COUNT...) and not an empty row

Fixes evaluation of empty aggregation without GROUP BY

---

lib/oxsdatatypes/src/decimal.rs

checked_div is only failing on division by 0...

xsd:decimal parsing: properly detect underflow

---

.mailmap

Before
❯ git shortlog -sn | head
1211	Tpt
46	Thomas Tanon
...
After
❯ git shortlog -sn | head
1259	Thomas Tanon
...

Make all Thomases into one

---

server/README.md
server/src/main.rs

Server: Improves systemd support

---

server/src/main.rs

Server: Use target graph name as base URI

---

lib/oxsdatatypes/src/boolean.rs
lib/oxsdatatypes/src/date_time.rs
lib/oxsdatatypes/src/decimal.rs
lib/oxsdatatypes/src/double.rs
lib/oxsdatatypes/src/duration.rs
lib/oxsdatatypes/src/float.rs
lib/oxsdatatypes/src/integer.rs
lib/src/sparql/eval.rs

Avoids internal overflow inside some decimal operations

XSD: Improves arithmetic computations

---

lib/sparql-smith/src/lib.rs

For some reasons explicit Arbitrary call seems way faster (95 iter/s after the change, less than 0.2 iter/s before the change)

Speeds up sparql_eval fuzzer

---

lib/src/sparql/plan_builder.rs

It can flip the MINUS operation out of the "disjoint" case

SPARQL: Prevents ForLoopLeftJoin with MINUS

---

lib/src/sparql/plan_builder.rs

It can inject variables leading to cardinality changes

Fixes hash left join into for loop left join optimization

---

lib/src/sparql/eval.rs

calendar subtraction: it should return xsd:dayTimeDuration following XPath

---

lib/oxrdf/src/triple.rs
lib/spargebra/src/term.rs
lib/src/storage/mod.rs
server/src/main.rs

Makes use of features in new Rust release

---

lib/oxrdfxml/src/error.rs
lib/oxrdfxml/src/lib.rs
lib/oxrdfxml/src/parser.rs
lib/oxttl/src/lib.rs
lib/oxttl/src/n3.rs
lib/oxttl/src/nquads.rs
lib/oxttl/src/ntriples.rs
lib/oxttl/src/toolkit/lexer.rs
lib/oxttl/src/toolkit/mod.rs
lib/oxttl/src/toolkit/parser.rs
lib/oxttl/src/trig.rs
lib/oxttl/src/turtle.rs
lib/sparesults/src/error.rs
lib/sparesults/src/xml.rs
lib/src/io/error.rs

Uses SyntaxError and ParseError everywhere

Refactor parsers error types

---

.github/workflows/artifacts.yml
.github/workflows/tests.yml
python/Cargo.toml
python/generate_stubs.py
python/pyproject.toml
python/requirements.dev.txt

Upgrades minimal Python version to 3.8

---

js/src/store.rs
lib/oxrdfio/src/serializer.rs
lib/src/io/write.rs
lib/src/store.rs
lib/tests/store.rs
python/src/io.rs
python/src/store.rs
server/src/main.rs

Allows to the user to control flushing

RDF serialization: removes implicit flush

---

fuzz/fuzz_targets/trig.rs
lib/oxrdf/src/dataset.rs

Allows to make the "distinguish" step work

Isomorphism: makes sure that new hashes depends on the old ones

---

js/README.md

JS: Adds more information on how to use dev tools

---

lib/oxrdfio/src/format.rs
lib/sparesults/src/lib.rs
server/src/main.rs

Makes media type to format more robust

---

.github/workflows/artifacts.yml
.github/workflows/tests.yml
Cargo.lock
Cargo.toml
cli/Cargo.toml
fuzz/Cargo.toml
fuzz/fuzz_targets/sparql_eval.rs
js/Cargo.toml
lib/Cargo.toml
lib/oxrdfio/Cargo.toml
lib/oxrdfxml/Cargo.toml
lib/oxsdatatypes/Cargo.toml
lib/oxsdatatypes/src/date_time.rs
lib/oxsdatatypes/src/double.rs
lib/oxsdatatypes/src/float.rs
lib/oxttl/Cargo.toml
lib/sparesults/Cargo.toml
lib/sparql-smith/Cargo.toml
lib/src/storage/backend/rocksdb.rs
lints/test_debian_compatibility.py
lints/test_spec_links.py
oxrocksdb-sys/Cargo.toml
python/src/io.rs
testsuite/Cargo.toml
testsuite/src/sparql_evaluator.rs

Let's keep compatibility with Debian unstable

Move back MSRV to 1.67

---

lib/src/sparql/eval.rs
testsuite/oxigraph-tests/sparql/manifest.ttl
testsuite/oxigraph-tests/sparql/small_iri_str.rq
testsuite/oxigraph-tests/sparql/small_iri_str.srx

SPARQL: makes sure that STR is working properly on small IRIs

---

lib/oxrdf/src/literal.rs
testsuite/src/parser_evaluator.rs
testsuite/tests/parser.rs

test suite MR: https://github.com/w3c/rdf-tests/pull/111

Testsuite: executes C14N tests

---

python/src/model.rs

They should behave like tuples

Python: annotate Triple and Quad with sequence behaviors

---

lib/spargebra/src/algebra.rs
lib/spargebra/src/parser.rs
lib/sparopt/src/algebra.rs
lib/sparopt/src/optimizer.rs
lib/src/sparql/eval.rs

SPARQL: refactor AggregateExpression

---

python/src/store.rs

Python Store.backup: allows pathlib

---

Cargo.lock
cli/Cargo.toml
cli/src/main.rs
fuzz/fuzz_targets/nquads.rs
fuzz/fuzz_targets/trig.rs
lib/Cargo.toml
lib/benches/store.rs
lib/oxrdf/Cargo.toml
lib/oxrdfio/src/parser.rs
lib/oxrdfxml/Cargo.toml
lib/oxrdfxml/src/parser.rs
lib/oxttl/Cargo.toml
lib/oxttl/src/lexer.rs
lib/oxttl/src/line_formats.rs
lib/oxttl/src/n3.rs
lib/oxttl/src/nquads.rs
lib/oxttl/src/ntriples.rs
lib/oxttl/src/terse.rs
lib/oxttl/src/trig.rs
lib/oxttl/src/turtle.rs
lib/spargebra/Cargo.toml
lib/src/store.rs
lints/test_debian_compatibility.py

Does not validate IRIs and language tags

Parsers: adds "unchecked" option for faster parsing

---

.github/workflows/artifacts.yml
.github/workflows/tests.yml
lib/src/storage/backend/rocksdb.rs
lib/src/storage/mod.rs
oxrocksdb-sys/build.rs

Fixes and ensures 32bits x86 support

---

cli/Dockerfile

Fixes Docker image

---

.github/workflows/artifacts.yml

Avoids partial releases in Pypi

CI: Uploads all Python wheels in one batch

---

.github/workflows/artifacts.yml
.github/workflows/tests.yml
lib/oxttl/src/n3.rs
lib/oxttl/src/terse.rs
lib/oxttl/src/toolkit/parser.rs
lib/oxttl/src/trig.rs
lib/oxttl/src/turtle.rs
lib/src/sparql/eval.rs
lib/src/storage/small_string.rs

oxttl: Exposes the base IRI

---

lib/oxsdatatypes/src/duration.rs
lib/oxttl/src/lexer.rs
lib/oxttl/src/n3.rs
lib/oxttl/src/terse.rs
lib/oxttl/src/trig.rs
lib/sparesults/src/csv.rs
lib/sparql-smith/src/lib.rs

Minor cleanup on the BNF comments - get rid of tabs and align them

Remove tabs from BNF comments

---

lib/oxrdf/src/dataset.rs
lib/oxrdf/src/graph.rs
lib/oxrdfxml/src/error.rs
lib/oxsdatatypes/src/decimal.rs
lib/oxttl/src/lexer.rs
lib/oxttl/src/line_formats.rs
lib/oxttl/src/n3.rs
lib/oxttl/src/terse.rs
lib/oxttl/src/toolkit/error.rs
lib/sparesults/src/error.rs
lib/sparesults/src/solution.rs
lib/spargebra/src/parser.rs
lib/src/sparql/eval.rs
rustfmt.toml

* A few match simplifications
* Order trait impl to match trait itself
* A few unneeded parenthesis
* One dup code de-duplication with a new func

Optimize some code, lints

---

lib/oxigraph/src/sparql/algebra.rs

Convert from spargebra Update to oxigraph Update

---

lib/sparesults/src/json.rs
lib/sparesults/src/lib.rs
lib/sparesults/src/parser.rs

Same design as the other parsers: a state machine fed by events (here JSON events)

Adds an async SPARQL JSON results reader

---

.github/workflows/tests.yml

CI: Read MSRV from Cargo.toml

---

js/README.md
js/src/store.rs
js/test/store.mjs

JS: Allows to set SPARQL base IRI and union graph

---

Cargo.lock
Cargo.toml
lib/oxrdf/Cargo.toml
lib/oxrdfio/Cargo.toml
lib/oxrdfxml/Cargo.toml
lib/oxttl/Cargo.toml
lib/sparesults/Cargo.toml
lib/spargebra/Cargo.toml
lib/sparopt/Cargo.toml

Bump versions and fixes spargebra version

---

cli/src/main.rs

CLI: Documents better the dump --graph argument

---

.github/ISSUE_TEMPLATE/bug_report.md
CHANGELOG.md
README.md
cli/Cargo.toml
cli/README.md
lib/oxigraph/README.md
lib/oxigraph/src/sparql/eval.rs
typos.toml

Thanks to @jonassmedegaard
Issue #842
Issue #843

Fixes some typos

---

lib/oxigraph/src/storage/backend/memory.rs
lib/oxigraph/src/storage/backend/mod.rs
lib/oxigraph/src/storage/backend/rocksdb.rs
lib/oxigraph/src/storage/memory.rs
lib/oxigraph/src/storage/mod.rs
lib/oxigraph/src/storage/rocksdb.rs
lib/oxigraph/src/store.rs
lib/oxigraph/tests/store.rs

Will be useful for specialization

Specialises Store implementation between RocksDB and in-memory

---

.gitmodules
cli/src/main.rs
cli/templates/query.html

Server: Vendors Yasgui instead of downloading it

---

fuzz/fuzz_targets/nquads.rs
fuzz/fuzz_targets/rdf_xml.rs
fuzz/fuzz_targets/trig.rs
fuzz/src/result_format.rs
lib/oxigraph/benches/store.rs
lib/oxrdfio/src/error.rs
lib/oxrdfio/src/parser.rs
lib/oxrdfxml/src/lib.rs
lib/oxrdfxml/src/parser.rs
lib/oxttl/src/line_formats.rs
lib/oxttl/src/n3.rs
lib/oxttl/src/nquads.rs
lib/oxttl/src/ntriples.rs
lib/oxttl/src/terse.rs
lib/oxttl/src/toolkit/lexer.rs
lib/oxttl/src/toolkit/mod.rs
lib/oxttl/src/toolkit/parser.rs
lib/oxttl/src/trig.rs
lib/oxttl/src/turtle.rs
lib/sparesults/src/csv.rs
lib/sparesults/src/json.rs
lib/sparesults/src/lib.rs
lib/sparesults/src/parser.rs
lib/sparesults/src/xml.rs

parsers: Adds parse_slice to parse directly from a slice

---

lib/oxigraph/src/storage/memory.rs

Makes portability easier. Not sure we need more than 2B in-memory transactions on 32bits platforms
Issue #913

Memory store: use usize for version counter

---

lib/oxsdatatypes/src/decimal.rs

Makes a Double test more relient

---

python/src/store.rs

Python: fixes Store.bulk_load to actually use the bulk loader

---

js/src/store.rs

JS: allows any iterator in Store constructor

---

lib/oxttl/src/chunker.rs
lib/oxttl/src/lib.rs
lib/oxttl/src/nquads.rs
lib/oxttl/src/ntriples.rs
lib/oxttl/src/toolkit/mod.rs
lib/oxttl/src/turtle.rs

Adds support for parallel parsing of NQuads

---

lib/oxigraph/src/sparql/mod.rs
lib/oxigraph/src/sparql/update.rs

Might cause slight discrepancies related to duplicated blank nodes

Removes automated REDUCED insertions

---

lib/oxigraph/src/sparql/eval.rs

We have a cache of the last 1M triples emitted that do not contain a blank node or a quoted triples. If the triple to emit is in there we don't emit it
Issue #525

SPARQL CONSTRUCT: avoid emitting multiple times the same triples

---

cli/src/main.rs
lib/oxigraph/src/storage/mod.rs
lib/oxigraph/src/storage/rocksdb.rs
lib/oxigraph/src/storage/rocksdb_wrapper.rs
lib/oxigraph/src/store.rs
lib/oxigraph/tests/store.rs
python/src/store.rs
python/tests/test_store.py

A lot of bugs, especially in RocksDB 9
If someone is willing to debug it, it would be much appreciated

Remove secondary storage

---

oxrocksdb-sys/build.rs

armv5te and riscv64gc: link with atomic lib

---

cli/src/cli.rs
cli/src/main.rs

CLI: Add the union-default-graph option to make SPARQL queries use the union of all graphs as the default graph

---

cli/build.rs
cli/src/cli.rs

CLI: Do not generate man pages for help commands

---

cli/src/main.rs
cli/src/service_description.rs
lib/sparesults/src/serializer.rs

HTTP: returns SPARQL service description

---

lib/oxigraph/src/sparql/eval.rs
testsuite/oxigraph-tests/sparql/manifest.ttl
testsuite/oxigraph-tests/sparql/regex_variable.rq
testsuite/oxigraph-tests/sparql/regex_variable.srx

Fixes variable regex evaluation

---

lib/sparopt/src/optimizer.rs

Remote SPARQL endpoint might have slightly different behaviors (extension functions, supported datatypes...)

Do not push filters in SERVICE

---

lib/sparesults/src/xml.rs

Avoids issues if the parser trims whitespaces

SPARQL XML query results: escape prefix and suffix whitespaces

---

lib/oxigraph/src/storage/memory.rs

It causes stack overflows because of too large chain of drop() calls

Memory store: avoid Arc in linked lists

---

lib/oxttl/src/toolkit/lexer.rs

Turtle: do not overload the buffer when there are no line jumps

---

Cargo.lock
fuzz/Cargo.toml
fuzz/fuzz_targets/sparql_query_eval.rs
lib/oxigraph/src/sparql/model.rs
lib/spareval/src/dataset.rs
lib/spargebra/src/query.rs
lib/spargeo/Cargo.toml
lib/spargeo/src/lib.rs
lib/sparql-smith/src/lib.rs
testsuite/Cargo.toml
testsuite/src/sparql_evaluator.rs
testsuite/tests/sparql.rs

No datatype normalization hence more conformant

SPARQL: Run the testsuite using Dataset

---

Cargo.lock
Cargo.toml
lib/oxigraph/src/sparql/dataset.rs
lib/spareval/src/dataset.rs
lib/spareval/src/eval.rs
lib/sparopt/Cargo.toml
lib/sparopt/src/algebra.rs
lib/sparopt/src/optimizer.rs
lib/sparopt/src/type_inference.rs
testsuite/oxigraph-tests/sparql-optimization/push_optional_filter_output.rq
testsuite/tests/sparql.rs

It should return all named graphs
Issue #1131

Properly evaluate `GRAPH ?g {}`

---

README.md

People no familiar with Rust may prefer Docker to try out oxygraph, so existence of Docker image should be mentioned.
Closes #1165.

Update README.md to mention Docker

---

lib/oxttl/src/lexer.rs
testsuite/oxigraph-tests/parser/decimal_dot_vs_triple_dot.nt
testsuite/oxigraph-tests/parser/decimal_dot_vs_triple_dot.ttl
testsuite/oxigraph-tests/parser/manifest.ttl

Fixes parsing of decimal at the end of the file

---

.github/workflows/tests.yml

Originally opened to identify if #1181 is an issue with my local setup.
Now adds missing macos test regardless.

chore: add windows and macos tests

---

fuzz/fuzz_targets/nquads.rs
lib/oxttl/src/line_formats.rs

Improve nquads error recovery

---

.github/workflows/artifacts.yml
.github/workflows/manylinux_build.sh
cli/Cargo.toml
cli/README.md
cli/pyproject.toml
lib/oxigraph/Cargo.toml
lib/oxjsonld/Cargo.toml
lib/oxrdf/Cargo.toml
lib/oxrdfio/Cargo.toml
lib/oxrdfxml/Cargo.toml
lib/oxsdatatypes/Cargo.toml
lib/oxttl/Cargo.toml
lib/sparesults/Cargo.toml
lib/spareval/Cargo.toml
lib/spargebra/Cargo.toml
lib/spargeo/Cargo.toml
lib/sparopt/Cargo.toml
lib/sparql-smith/Cargo.toml
oxrocksdb-sys/Cargo.toml
testsuite/Cargo.toml

- Reuse oxigraph cli wheels for plain binaries
- Validate wheels
- Factorize code

CI: improve builds

---

lib/oxigraph/src/storage/rocksdb.rs

Bulk loader: remove SST files on failure

---

lib/oxttl/src/lexer.rs
testsuite/oxigraph-tests/parser/bnode_trailing_dot.nt
testsuite/oxigraph-tests/parser/bnode_trailing_dot.ttl
testsuite/oxigraph-tests/parser/manifest.ttl
testsuite/oxigraph-tests/parser/pname_trailing_dot.nt
testsuite/oxigraph-tests/parser/pname_trailing_dot.ttl

Turtle: Fixes parsing of blank nodes at the end of files

---

lib/oxttl/src/trig.rs

Turtle: use the longest prefix during serialization

---

fuzz/fuzz_targets/sparql_query_eval.rs
lib/oxigraph/src/sparql/dataset.rs
lib/oxigraph/src/sparql/http.rs
lib/oxigraph/src/sparql/mod.rs
lib/oxigraph/src/store.rs
lib/sparesults/src/xml.rs
lib/spareval/README.md
lib/spareval/src/dataset.rs
lib/spareval/src/eval.rs
lib/spareval/src/lib.rs
lib/spareval/src/model.rs
lib/spareval/src/service.rs
python/src/sparql.rs
python/src/store.rs
testsuite/src/sparql_evaluator.rs

SPARQL evaluator: allows to bound dataset lifetime

---

lib/oxjsonld/src/expansion.rs
testsuite/oxigraph-tests/jsonld/aliased_type.jsonld
testsuite/oxigraph-tests/jsonld/aliased_type.nq
testsuite/oxigraph-tests/jsonld/manifest.jsonld
testsuite/tests/oxigraph.rs

Aliasing was not taken into account

JSON-LD: fixing aliased @type lookup

---

testsuite/tests/oxigraph.rs

Run oxigraph_optimizer_testsuite only on little endian

---

lib/oxigraph/tests/store.rs

RocksDB backward compatibility test: run only on 64 bits little endian
